
CREATE TABLE test
(
  sid INT NOT NULL,
  dt TIMESTAMP NOT NULL,
  value DOUBLE NOT NULL
);

PARTITION TABLE sensordata ON COLUMN sid;

CREATE PROCEDURE insert_sd
AS
   INSERT INTO test VALUES(?,?,?);

PARTITION PROCEDURE insert_sd ON TABLE test COLUMN sid PARAMETER 0;
